import { writeFile } from "fs/promises";

export const generateTypes = async (events, outDir) => {
  const content = `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

export type FathomRegisteredEventName = ${
    events.length > 0
      ? events.map((event) => `"${event.name}"`).join(" | ")
      : "any"
  };

export interface FathomRegisteredEvent {
  id: string;
  object: "event";
  name: FathomRegisteredEventName;
  currency: string | null;
  created_at: string;
}
`;

  await writeFile(outDir, content);
};
