export const generateTypes = (events) => {
  const content = `
  // THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

  export type FathomRegisteredEventName = ${events
    .map((event) => `"${event.name}"`)
    .join(" | ")};
  
  export interface FathomRegisteredEvent {
    id: string;
    object: 'event';
    name: FathomRegisteredEventName;
    currency: string | null;
    created_at: string;
  }
  `;

  return content;
};
